/**
 * The function Vercel serves. Everything real is in `_entry.ts`.
 *
 * `_bundle.js` is generated by `scripts/build-api.mjs` during the build, and is
 * the whole API inlined into one file. The indirection exists because Vercel
 * compiles each of the kiosk's own TypeScript files to ESM but does not compile
 * the workspace packages they import, and five of those export raw TypeScript:
 * @atrium/skill-graph, @atrium/schema and the three capture apps. At runtime
 * Node was asked to import `…/@atrium/skill-graph/src/app.ts` and could not —
 * a deployment that built cleanly and then answered 500 to everything.
 *
 * Bundling ahead of time settles it where it belongs. esbuild resolves the
 * workspace packages the same way vite and tsx do, and hands Vercel a single
 * file with no imports left to resolve.
 *
 * Kept as the entry point (rather than generating `[...path].js` directly) so
 * that function detection still works off a file in the repo: Vercel decides
 * what the functions are from the source tree, and a file that only appears
 * during the build may never be seen.
 */

export { default } from './_bundle.js'
