/**
 * Resolving handwritten move text against the board.
 *
 * The OCR step is deliberately literal: it records `bg4` and `b94` exactly as
 * written, because the misspelling is the diagnostic signal. This is the stage
 * that decides `bg4` was a legal bishop move and `b94` was not a move at all —
 * and, crucially, says which of those two answers it is confident about.
 *
 * Ported from chess-karma's `validator.py` onto chess.js. Three passes:
 *
 *   0/1. Try the parser's candidates in order against the live position.
 *   2.   A bare destination like `d4` — sweep every piece that can reach it.
 *   3.   Last resort: score every legal move by similarity to what the child
 *        wrote and take the best, with a two-ply look-ahead as the tiebreak.
 *        Does this choice keep the *next* moves legal?
 *
 * Every move comes back tagged. That tag is the deliverable as much as the SAN
 * is: a move resolved at pass 0 needs no human, and a move resolved at pass 3
 * is by construction the one worth a second look.
 */

import { Chess, type Move } from 'chess.js'
import { generateCandidates } from './normalize'
import { sanSimilarity } from './similarity'

/**
 * How a move was resolved, in descending order of confidence.
 *
 * `missing` and `failed` are different failures: `missing` is an empty cell the
 * board could not fill in, `failed` is text that could not be made into any
 * legal move. Both are for a human; only one is the child's fault.
 */
export type MoveStatus = 'ok' | 'normalized' | 'corrected' | 'inferred' | 'missing' | 'failed'

export interface RawMovePair {
  n: number
  w?: string | null
  b?: string | null
}

export interface ValidatedMove {
  n: number
  side: 'white' | 'black'
  /** Exactly what the child wrote. Never rewritten. */
  raw: string | null
  /** The resolved move in standard algebraic notation, or null if unresolved. */
  san: string | null
  uci: string | null
  status: MoveStatus
}

/**
 * python-chess's SAN grammar, which is looser than canonical SAN on purpose:
 * the capture `x` is optional and the check mark is ignored. That leniency is
 * load-bearing — it is why `Bb2` resolves to `Bxb2` at full confidence instead
 * of falling through to the similarity pass.
 */
const SAN_REGEX = /^([NBKRQ])?([a-h])?([1-8])?[-x]?([a-h][1-8])(=?[nbrqkNBRQK])?[+#]?$/

const KINGSIDE = new Set(['O-O', 'O-O+', 'O-O#', '0-0', '0-0+', '0-0#'])
const QUEENSIDE = new Set(['O-O-O', 'O-O-O+', 'O-O-O#', '0-0-0', '0-0-0+', '0-0-0#'])

/**
 * Play a move by coordinates rather than by SAN.
 *
 * The key is omitted rather than set to undefined when there is no promotion,
 * because `exactOptionalPropertyTypes` treats those as different things and
 * chess.js only accepts the former.
 */
function play(board: Chess, move: Move): void {
  board.move(
    move.promotion
      ? { from: move.from, to: move.to, promotion: move.promotion }
      : { from: move.from, to: move.to },
  )
}

/** Square name to python-chess's index: a1 = 0, h8 = 63. */
function squareIndex(square: string): number {
  return square.charCodeAt(0) - 97 + 8 * (Number(square[1]) - 1)
}

/** python-chess yields promotions queen, rook, bishop, knight — in that order. */
const PROMOTION_ORDER: Record<string, number> = { q: 0, r: 1, b: 2, n: 3 }

/**
 * Which batch of python-chess's generator a move belongs to.
 *
 * `generate_pseudo_legal_moves` emits in fixed groups: piece moves, then
 * castling, then pawn captures, then single advances, then doubles, then en
 * passant.
 */
function generationGroup(move: Move): number {
  if (move.piece !== 'p') return move.flags.includes('k') || move.flags.includes('q') ? 1 : 0
  if (move.flags.includes('e')) return 5
  if (move.from[0] !== move.to[0]) return 2 // a pawn changing file is a capture
  if (move.flags.includes('b')) return 4
  return 3
}

/**
 * The legal moves of a position, in python-chess's generation order.
 *
 * This is not cosmetic and it is not tidiness. Passes 2 and 3 both take the
 * *first* move that wins, and Python's `sorted` is stable, so on any tie —
 * which is every unresolvable cell, where all legal moves score zero
 * similarity — the generator's order silently decides what the scoresheet is
 * read as. chess.js walks squares a1→h8; python-chess walks them h8→a1 within
 * each group. Left alone, that difference alone changed one move in the
 * fixtures and every move after it, through position drift.
 *
 * So the order is reproduced rather than accepted: within each group, by
 * origin square descending, then destination square descending.
 */
function legalMoves(board: Chess): Move[] {
  return board.moves({ verbose: true }).sort((a, b) => {
    const group = generationGroup(a) - generationGroup(b)
    if (group !== 0) return group
    // Pawn advances are generated by destination alone; everything else walks
    // origin squares first.
    if (generationGroup(a) < 3 || generationGroup(a) === 5) {
      const from = squareIndex(b.from) - squareIndex(a.from)
      if (from !== 0) return from
    }
    const to = squareIndex(b.to) - squareIndex(a.to)
    if (to !== 0) return to
    return (PROMOTION_ORDER[a.promotion ?? 'q'] ?? 0) - (PROMOTION_ORDER[b.promotion ?? 'q'] ?? 0)
  })
}

/**
 * Find the legal move a SAN string denotes, or null.
 *
 * Null covers both "no such legal move" and "more than one" — an ambiguous
 * string tells us nothing, so it is not a match.
 */
export function parseSan(legal: Move[], san: string): Move | null {
  if (KINGSIDE.has(san)) return legal.find((m) => m.san.startsWith('O-O') && !m.san.startsWith('O-O-O')) ?? null
  if (QUEENSIDE.has(san)) return legal.find((m) => m.san.startsWith('O-O-O')) ?? null

  const match = SAN_REGEX.exec(san)
  if (!match) return null

  const [, pieceLetter, fromFile, fromRank, to, promoRaw] = match
  if (!to) return null
  const promotion = promoRaw ? promoRaw[promoRaw.length - 1]!.toLowerCase() : undefined

  let pool = legal.filter((m) => m.to === to)
  if (fromFile) pool = pool.filter((m) => m.from[0] === fromFile)
  if (fromRank) pool = pool.filter((m) => m.from[1] === fromRank)

  if (pieceLetter) {
    const type = pieceLetter.toLowerCase()
    pool = pool.filter((m) => m.piece === type)
  } else if (fromFile && fromRank) {
    // Both coordinates and no piece letter is a fully specified move, e.g.
    // 'e2e4'. Take it literally rather than reading it as a pawn move.
    const from = fromFile + fromRank
    return (
      legal.find((m) => m.from === from && m.to === to && (m.promotion ?? undefined) === promotion) ?? null
    )
  } else {
    pool = pool.filter((m) => m.piece === 'p')
    // A pawn move with no file given is a push, not a capture.
    if (!fromFile) pool = pool.filter((m) => m.from[0] === to[0])
  }

  const matched = pool.filter((m) => (m.promotion ?? undefined) === promotion)
  return matched.length === 1 ? matched[0]! : null
}

/**
 * How many of the next two plies stay legal if this move is played.
 *
 * The tiebreak that makes the similarity pass more than a guess: a wrong move
 * usually strands the moves after it, and a right one does not.
 */
function futureAnchorScore(board: Chess, move: Move, futureRaws: string[]): number {
  const test = new Chess(board.fen())
  play(test, move)

  let score = 0
  for (const raw of futureRaws.slice(0, 2)) {
    const legal = legalMoves(test)
    let found: Move | null = null
    for (const c of generateCandidates(raw)) {
      found = parseSan(legal, c)
      if (found) break
    }
    if (!found) continue
    score++
    play(test, found)
  }
  return score
}

/** The three-pass resolution for a single half-move. */
export function bestLegalMove(
  board: Chess,
  raw: string | null,
  candidates: string[],
  futureRaws: string[] = [],
): { move: Move | null; san: string; status: MoveStatus } {
  if (!raw && candidates.length === 0) return { move: null, san: '', status: 'failed' }

  const legal = legalMoves(board)

  // Passes 0 and 1 — the parser already ordered these best-first, so the index
  // is the confidence: the first candidate is what the child wrote, anything
  // later is a repair.
  for (let i = 0; i < candidates.length; i++) {
    const move = parseSan(legal, candidates[i]!)
    if (move) return { move, san: move.san, status: i === 0 ? 'ok' : 'normalized' }
  }

  // Pass 2 — a bare destination. Any piece that reaches it is a better guess
  // than the similarity pass would make.
  if (raw) {
    const body = raw.toLowerCase().replace(/[+#]+$/, '').replace(/x/g, '')
    if (body.length === 2 && 'abcdefgh'.includes(body[0]!) && '12345678'.includes(body[1]!)) {
      const hit = legal.find((m) => m.to === body)
      if (hit) return { move: hit, san: hit.san, status: 'normalized' }
    }
  }

  // Pass 3 — rank every legal move by how much it looks like what was written.
  if (!raw || legal.length === 0) return { move: null, san: '', status: 'failed' }

  const scored = [...legal].sort((a, b) => sanSimilarity(raw, b.san) - sanSimilarity(raw, a.san))
  const best = scored[0]!

  if (futureRaws.length > 0 && scored.length > 1) {
    /*
     * Rank the plausible few by look-ahead, first maximum wins.
     *
     * "First" means first in the generation order fixed above, which is what
     * decides a cell where several moves tie on both similarity and
     * look-ahead — i.e. every genuinely unresolvable cell. Moves decided here
     * are always tagged `corrected`: a human is being asked to look either way.
     */
    const top = scored.slice(0, 4)
    let bestMove = top[0]!
    let bestScore = futureAnchorScore(board, bestMove, futureRaws)
    for (const candidate of top.slice(1)) {
      const score = futureAnchorScore(board, candidate, futureRaws)
      if (score > bestScore) {
        bestScore = score
        bestMove = candidate
      }
    }
    return { move: bestMove, san: bestMove.san, status: 'corrected' }
  }

  return { move: best, san: best.san, status: 'corrected' }
}

/**
 * Walk a whole scoresheet, resolving each move against the position the
 * previous ones produced.
 *
 * Stops at checkmate or stalemate: anything written past the end of the game is
 * not a move, and pretending to resolve it would invent history.
 */
export function validateGame(rawMoves: RawMovePair[]): ValidatedMove[] {
  const board = new Chess()
  const results: ValidatedMove[] = []

  const flat: { n: number; side: 'white' | 'black'; raw: string | null }[] = []
  for (const m of rawMoves) {
    flat.push({ n: m.n, side: 'white', raw: m.w ?? null })
    flat.push({ n: m.n, side: 'black', raw: m.b ?? null })
  }

  for (let idx = 0; idx < flat.length; idx++) {
    if (board.isGameOver()) break
    const { n, side, raw } = flat[idx]!

    if (raw === null) {
      // An empty cell with exactly one legal reply writes itself. Any other
      // number of options and the cell stays empty for a human to fill.
      const legal = legalMoves(board)
      if (legal.length === 1) {
        const only = legal[0]!
        // SAN is read before the move is played, which is the one place this
        // port deliberately diverges: the original computes it afterwards,
        // against the position the move already changed.
        results.push({ n, side, raw: null, san: only.san, uci: only.lan, status: 'inferred' })
        play(board, only)
      } else {
        results.push({ n, side, raw: null, san: null, uci: null, status: 'missing' })
      }
      continue
    }

    const futureRaws = flat
      .slice(idx + 1, idx + 5)
      .map((f) => f.raw)
      .filter((r): r is string => Boolean(r))

    const { move, san, status } = bestLegalMove(board, raw, generateCandidates(raw), futureRaws)

    if (move) {
      play(board, move)
      results.push({ n, side, raw, san, uci: move.lan, status })
    } else {
      results.push({ n, side, raw, san: null, uci: null, status: 'failed' })
    }
  }

  return results
}
